spring:
  datasource:
    master:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/mytest
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/testdb
      driver-class-name: com.mysql.cj.jdbc.Driver    
  jta:
    atomikos: 
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

          
